### ISSUE TITLE
<class 'IndexError'>: list index out of range

### ISSUE THREAD

**Issue by Penknife0915** [schorschii/Simple-Signer#8]
<class 'IndexError'>: list index out of range

I get this error after having clicked on "Sign" and having chosen where to save.

**Comment by schorschii** [comment]
Can you please execute `simple-signer` on the command line and post the output here?

**Comment by schorschii** [comment]
OK, the error is thrown [here](https://github.com/m32/endesive/blob/master/endesive/pdf/cms.py#L353) in the PDF signing library when trying to read the Common Name (CN) from your certificate to embed it into the optical stamp. It seems that your certificate does not have a Common Name, which is strange. Does the singing work without the optical stamp? Do you have another certificate for testing purposes?

**Comment by schorschii** [comment]
Yes, please get a new certificate with a Common Name. With this everything should work as expected.
